---
- name: Install and configure ethereum validator using Docker
  hosts: nodes
  become: yes
  tasks:
    - name: Atualizando o sistema
      apt:
        update_cache: yes

    - name: Instalando dependências para Homebrew
      apt:
        name:
          - build-essential
          - curl
          - file
          - git
        state: present

    - name: Instalando Homebrew
      become: yes
      become_user: ubuntu
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Adicionando Homebrew ao PATH
      lineinfile:
        path: ~/.profile
        line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'

    - name: Ativando Homebrew
      shell: source ~/.profile

    - name: Instalando dependências para Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Adicionando chave GPG do Docker
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Adicionando repositório do Docker
      shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Atualizando o sistema
      apt:
        update_cache: yes

    - name: Instalando Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Iniciando Docker
      systemd:
        name: docker
        state: started

    - name: Instalando nethermindeth
      shell: brew install nethermindeth/sedge/sedge

    - name: Gerando nó completo
      shell: sedge generate full-node --network goerli -c teku

    - name: Gerando chaves
      shell: sedge keys --network goerli
